/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_superlab_ss_Mp4RawDataFixer */

#ifndef _Included_com_superlab_ss_Mp4RawDataFixer
#define _Included_com_superlab_ss_Mp4RawDataFixer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_superlab_ss_Mp4RawDataFixer
 * Method:    setAVCParameters
 * Signature: ([BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_superlab_ss_Mp4RawDataFixer_setAVCParameters
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_superlab_ss_Mp4RawDataFixer
 * Method:    setAACAudioSpecificConfig
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_superlab_ss_Mp4RawDataFixer_setAACAudioSpecificConfig
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_superlab_ss_Mp4RawDataFixer
 * Method:    extractAVStream
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_superlab_ss_Mp4RawDataFixer_extractAVStream
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
